swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /scores:
    get:
      operationId: scores.read_all
      tags:
        - Scores
      summary: Read the entire set of scores, sorted by date
      description: Read the entire set of scores, sorted by date
      responses:
        200:
          description: Successfully set operation
          schema:
            type: array
            items:
              properties:
                gameNumber:
                  type: string
                gameDate:
                  type: string
                Dan:
                  type: string
                Will:
                  type: string
                Ben:
                  type: string
                Sven:
                  type: string
    post:
      operationId: scores.create
      tags:
        - Scores
      summary: Create a record
      description: Create a new record
      parameters:
        - name: scores
          in: body
          description: scores to create
          required: True
          schema:
              properties:
                winner:
                  type: string
                runnerup:
                  type: string
      responses:
        201:
          description: Successfully created score
          schema:
              properties:
                gameNumber:
                  type: string
                gameDate:
                  type: string
                Dan:
                  type: string
                Will:
                  type: string
                Ben:
                  type: string
                Sven:
                  type: string